version: '3.9'
services:
    archivebox:
        container_name: archivebox
        image: archivebox/archivebox:0.6.3
        ports:
            - ${APP_PORT}:8000
        environment:
            - ALLOWED_HOSTS=*
            - MEDIA_MAX_SIZE=750m
        volumes:
            - ${APP_DATA_DIR}/data:/data
        restart: unless-stopped
        networks:
          - tipi_main_network
